export { default as Home } from './home';
export { default as Events } from './events';
export { default as Community } from './community';
export { default as Contact } from './contact';
export { default as Products } from './products';
export { default as Team } from './team';
export { default as Waitlist } from './waitlist';
export { default as ErrorPage } from './notFound';
export { default as Test } from './team';
